<%-- 
    Document   : view_customer
    Created on : 03-Apr-2023, 11:58:55 pm
    Author     : bas200193
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
        <html lang=\"en\" >\n");
        <head>\n");
          <meta charset=\"UTF-8\">\n");
            <title>CodePen - Student Profile</title>\n");
                <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
        
                <link href=\"https://fonts.googleapis.com/css?family=Lato:300,400,700,900&display=swap\" rel=\"stylesheet\"><link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/css/bootstrap.min.css'>\n");
               <!--<link rel='stylesheet' href='https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css'><link rel=\"stylesheet\" href=\"./style.css\">-->\n");
               <style>\n");
                    body {\n");
                        padding: 0;\n");
                     margin: 0;\n");
                       font-family: 'Lato', sans-serif;\n");
                      color: #000;\n");
                    }\n");
        
                    .student-profile .card {\n");
                        border-radius: 10px;\n");
                   }\n");
        
                   .student-profile .card .card-header .profile_img {\n");
                       width: 150px;\n");
                        height: 150px;\n");
                        object-fit: cover;\n");
                       margin: 10px auto;\n");
                        border: 10px solid #ccc;\n");
                    border-radius: 50%;\n");
                    }\n");
        
                   .student-profile .card h3 {\n");
                        font-size: 20px;\n");
               paydebtamount        font-weight: 700;\n");
                    }\n");
        
                    .student-profile .card p {\n");
        out.write("                font-size: 16px;\n");
        out.write("                color: #000;\n");
        out.write("            }\n");
        out.write("\n");
        out.write("            .student-profile .table th,\n");
        out.write("            .student-profile .table td {\n");
        out.write("                font-size: 14px;\n");
        out.write("                padding: 5px 10px;\n");
        out.write("                color: #000;\n");
        out.write("            }\n");
        out.write("            .button-67 {\n");
        out.write("            align-items: center;\n");
        out.write("            background: #CCD1D1;\n");
        out.write("            /*background: #C39BD3;*/\n");
        out.write("            /*background: #f5f5fa;*/\n");
        out.write("            border: 0;\n");
        out.write("            border-radius: 8px;\n");
                   box-shadow: -10px -10px 30px 0 #fff,10px 10px 30px 0 #1d0dca17;\n");
                   box-sizing: border-box;\n");
                    color: #2a1f62;\n");
                    cursor: pointer;\n");
                   display: flex;\n");
                   font-family: \"Cascadia Code\",Consolas,Monaco,\"Andale Mono\",\"Ubuntu Mono\",monospace;\n");
                font-size: 1rem;\n");
                   justify-content: center;\n");
                line-height: 1.5rem;\n");
                   padding: 15px;\n");
                   position: relative;\n");
                   text-align: left;\n");
                  transition: .2s;\n");
                  user-select: none;\n");
                   -webkit-user-select: none;\n");
                 touch-action: manipulation;\n");
                  white-space: pre;\n");
                  width: max-content;\n");
                 word-break: normal;\n");
                  word-spacing: normal;\n");
                 }\n");
        
                    .button-67:hover {\n");
                    background: #f8f8ff;\n");
                   box-shadow: -15px -15px 30px 0 #fff, 15px 15px 30px 0 #1d0dca17;\n");
                }\n");
        
                   @media (min-width: 768px) {\n");
                    .button-67 {\n");
                    padding: 24px;\n");
                   }\n");
                  }\n");
        
                </style>\n");
            </head>\n");
            <body>\n");
                <!-- partial:index.partial.html -->\n");
               <!-- Student Profile -->\n");
               <div class=\"student-profile py-4\">\n");
                   <div class=\"container\">\n");
                      <div class=\"row\">\n");
                          <div class=\"col-lg-4\">\n");
                              <div class=\"card shadow-sm\">\n");
                                  <div class=\"card-header bg-transparent text-center\">\n");
                                        <img class=\"profile_img\" src=\"https://placeimg.com/640/480/arch/any\" alt=\"\">\n");
                                        <h3>" + customer.getName() + "</h3>\n");
                                    </div>\n");
                                    <div class=\"card-body\">\n");
                                       <p class=\"mb-0\"><strong class=\"pr-1\">Customer ID:</strong>" + customer.getId() + "</p>\n");
                                    <p class=\"mb-0\"><strong class=\"pr-1\">Status:</strong>" + (customer.isStatus() ? "Active" : "InActive") + "</p>\n");
                                    </div>\n");
                                </div>\n");
                           </div>\n");
                         <div class=\"col-lg-8\">\n");
                                <div class=\"card shadow-sm\">\n");
                                  <div class=\"card-header bg-transparent border-0\">\n");
                                        <h3 class=\"mb-0\"><i class=\"far fa-clone pr-1\"></i>General Information</h3>\n");
                                   </div>\n");
                                   <div class=\"card-body pt-0\">\n");
                                      <table class=\"table table-bordered\">\n");
                                       <tr>\n");
                                                <th width=\"30%\">Phone no</th>\n");
                                               <td width=\"2%\">:</td>\n");
                                               <td>" + customer.getPhone() + "</td>\n");
                                           </tr>\n");
                                           <tr>\n");
        out.write("                                        <th width=\"30%\">Aadhaar No	</th>\n");
        out.write("                                        <td width=\"2%\">:</td>\n");
        out.write("                                        <td>" + customer.getAadhaar() + "</td>\n");
        out.write("                                    </tr>\n");
        out.write("                                    <tr>\n");
        out.write("                                        <th width=\"30%\">Gender</th>\n");
        out.write("                                        <td width=\"2%\">:</td>\n");
        out.write("                                        <td>Male</td>\n");
        out.write("                                    </tr>\n");
        out.write("                                    <tr>\n");
        out.write("                                        <th width=\"30%\">Debt Balance</th>\n");
        out.write("                                        <td width=\"2%\">:</td>\n");
        out.write("                                        <td>" + customer.getDebtBalance() + "</td>\n");
        out.write("                                    </tr>\n");
//        out.write("                                    <tr>\n");
//        out.write("                                        <th width=\"30%\">Wallet Balance</th>\n");
//        out.write("                                        <td width=\"2%\">:</td>\n");
//        out.write("                                        <td>" + customer.getWalletBalance() + "</td>\n");
//        out.write("                                    </tr>\n");
        out.write("                                </table>\n");
        out.write("                            <div class=\"card-header bg-transparent border-0\">\n");
        out.write("                                <h3 class=\"mb-0\"><i class=\"far fa-clone pr-1\"></i>Address</h3>\n");
        out.write("                            </div>\n");
        out.write("                                <table class=\"table table-bordered\">\n");
        out.write("                                    <tr>\n");
        out.write("                                        <th width=\"30%\">Door/House no</th>\n");
        out.write("                                        <td width=\"2%\">:</td>\n");
        out.write("                                        <td>" + customer.getAddress().getHouseNo() + "</td>\n");
        out.write("                                    </tr>\n");
        out.write("                                    <tr>\n");
        out.write("                                        <th width=\"30%\">Street	</th>\n");
        out.write("                                        <td width=\"2%\">:</td>\n");
        out.write("                                        <td>" + customer.getAddress().getStreet() + "</td>\n");
        out.write("                                    </tr>\n");
        out.write("                                    <tr>\n");
        out.write("                                        <th width=\"30%\">Distric</th>\n");
        out.write("                                        <td width=\"2%\">:</td>\n");
        out.write("                                        <td>" + customer.getAddress().getDistric() + "</td>\n");
        out.write("                                    </tr>\n");
        out.write("                                    <tr>\n");
        out.write("                                        <th width=\"30%\">State</th>\n");
        out.write("                                        <td width=\"2%\">:</td>\n");
        out.write("                                        <td>" + customer.getAddress().getState() + "</td>\n");
        out.write("                                    </tr>\n");
        out.write("                                    <tr>\n");
        out.write("                                        <th width=\"30%\">Pincode</th>\n");
        out.write("                                        <td width=\"2%\">:</td>\n");
        out.write("                                        <td>" + customer.getAddress().getPincode() + "</td>\n");
        out.write("                                    </tr>\n");
        out.write("                                </table>\n");
        out.write("                                </table>\n");
        out.write("                            </div>\n");
        out.write("                    </div>\n");
        out.write("                </div>\n");
        out.write("            </div>\n");
        out.write("        </div>\n");
        out.write("\n");
